--- #YAML:1.0
name:               Perl-Meta
version:            0.02
abstract:           Extract metadata from perl/pod text.
author:
    - Alexandr Ciornii <alexchorny@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    perl:  5.005
resources:
    repository:  http://svn.ali.as/cpan/trunk/Perl-Meta
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
